apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-example
  description: |
    Backstage is an open-source developer portal that puts the developer experience first.
  links:
    - title: Website
      url: http://backstage.io
    - title: Documentation
      url: https://backstage.io/docs
    - title: Storybook
      url: https://backstage.io/storybook
    - title: Discord Chat
      url: https://discord.com/invite/EBHEGzX
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/adr-location: docs/adrs
    quay.io/repository-slug: jetstack/cert-manager-controller
spec:
  type: library
  owner: CNCF
  lifecycle: experimental
